version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
